### ISSUE TITLE
Weekly issue 111：延至 2018/1/8 出刊

### ISSUE THREAD

**Issue by saiday** [CodeTengu/HyakkiYagyo#139]
接著兩週適逢聖誕節跟元旦，我提議順勢休刊兩週，這樣大家可以有比較完整的 ~~被假期~~ 假期安排。

如果大家同意的話，下一期就延到 2018/1/8 出刊囉，有其他意見或建議也請提出來～

---

https://my.curated.co/codetengu/issues/30932

當期陣容：

@chiahsien
@kkdai  
@yhsiang 

各位假期愉快！

**Comment by tzangms** [comment]
好貼心

**Comment by fukuball** [comment]
太棒了～

**Comment by yhsiang** [comment]
讚拉！

**Comment by mingder78** [comment]
大家，聖誕節快樂

**Comment by chiahsien** [comment]
我好囉

**Comment by kkdai** [comment]
我也好了

**Comment by yhsiang** [comment]
我也好囉！

**Comment by saiday** [comment]
已排程， 2018 啦！
