### ISSUE TITLE
Weekly issue 115： 2018/02/05 出刊

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#144]
https://my.curated.co/codetengu/issues/31465

本期陣容：

- @vinta
- @kkdai
- @johnlinvc

麻煩各位了，有問題請說！

**Comment by kkdai** [comment]
我好了... 這次三篇加一個 random cool thing about MHW   (應該會被扁)

**Comment by vinta** [comment]
@kkdai 哈哈哈你竟然還有玩魔物獵人？！你的時間管理能力果然太驚人了！

**Comment by saiday** [comment]
@johnlinvc 好像寫到一半中斷了？
那我先這樣排程囉！

再請 @johnlinvc 報個平安！

**Comment by johnlinvc** [comment]
@saiday 
@vinta 
Done, 不過他發的時候會發最新的內容嗎？有需要重新排程嗎？
