### ISSUE TITLE
Weekly issue 117：2018/03/05 出刊 - fukuball, kako0507, wancw

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#146]
https://my.curated.co/codetengu/issues/31694

本期陣容：

- @fukuball
- @kako0507
- @wancw

麻煩各位了，有問題請說！

**Comment by vinta** [comment]
怕大家過了個年忘記，這禮拜要記得寫 weekly 啊 👍

**Comment by wancw** [comment]
我還真的忘了這期有我⋯⋯

**Comment by wancw** [comment]
done!

**Comment by vinta** [comment]
已排程，關！
