### ISSUE TITLE
Weekly issue 118：2018/03/12 出刊 - saiday, kkdai, drumrick

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#147]
https://my.curated.co/codetengu/issues/31931

本期陣容：

- @saiday
- @kkdai
- @drumrick

麻煩各位了，有問題請說！

**Comment by kkdai** [comment]
我這邊好了

**Comment by saiday** [comment]
大家好像都好了，我也好了！

已排程！

**Comment by drumrick** [comment]
我這邊也好了。
@saiday 我放了一個徵才訊息
但是我 category 沒有 "工作機會" 這個選項可以選
可你麻煩你幫我調嗎？

**Comment by saiday** [comment]
哦哦，看來工作機會這個 category 要在 [Sponsorships](https://my.curated.co/codetengu/sponsors) 解鎖

我想你應該有權限可以新增？你試試看！

**Comment by drumrick** [comment]
我填好了。謝謝。

**Comment by saiday** [comment]
nice!
