### ISSUE TITLE
Weekly issue 119：2018/03/19 出刊 - tzangms, uranusjr, johnlinvc

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#148]
https://my.curated.co/codetengu/issues/32004

本期陣容：

- @tzangms
- @uranusjr
- @johnlinvc

麻煩各位了，有問題請說！

**Comment by johnlinvc** [comment]
👍

**Comment by johnlinvc** [comment]
done

**Comment by uranusjr** [comment]
寫完了了了了了了了

**Comment by tzangms** [comment]
拍謝,  我因為前陣子關掉了 Github notification, 所以沒注意到我有排班, 囧

**Comment by vinta** [comment]
@tzangms 原來如此，那這禮拜的 [Issue 120](https://github.com/CodeTengu/HyakkiYagyo/issues/149) 你可以嗎？

**Comment by tzangms** [comment]
結果我還是沒收到這個通知, 加上上禮拜放假 ...  我現在打開了 ... 
下禮拜讓我贖罪 ( 跪
