### ISSUE TITLE
Weekly issue 121：2018/04/02 出刊 - tzangms, fukuball, yhsiang

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#150]
https://my.curated.co/codetengu/issues/32221

本期陣容：

- @tzangms
- @fukuball
- @yhsiang

麻煩各位了，有問題請說！

**Comment by yhsiang** [comment]
我好了！

不好意思前陣子太忙 QQ

**Comment by tzangms** [comment]
我記得 已經寫一則了 正在寫第二則 搞定會上來喊一聲！ 謝謝！

**Comment by tzangms** [comment]
我寫好了! 有誠意的兩篇 ~

**Comment by tzangms** [comment]
另外，先半年不要排我好了，我最近太低潮了，而且跟技術快沒有關係了，先讓我當游擊隊一陣子，我不定期亂入，謝謝!

**Comment by vinta** [comment]
好！搞定！
