### ISSUE TITLE
Weekly issue 122 will be published on 2018/04/09 - @saiday, @chiahsien, @allanlei

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#151]
See: https://my.curated.co/codetengu/issues/32284

Curators of the week:

- @saiday
- @chiahsien
- @allanlei

And yes, we have a new member, @allanlei, one of the most outstanding software engineers I ever met. He joins us this week! Welcome! 👏 👏 👏

P.S. Allan is from Canada and currently works in Taiwan, so he will write weekly columns in English. Yeah, go international!

**Comment by kako0507** [comment]
這禮拜我不太方便弄😰有人可以幫忙 cover 一下嗎？

**Comment by vinta** [comment]
@saiday 有沒有辦法頂一下？

**Comment by saiday** [comment]
我可以～

**Comment by chiahsien** [comment]
我好囉
