### ISSUE TITLE
Weekly issue 123 will be published on 2018/04/16 - @uranusjr, @kkdai, @drumrick

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#152]
See: https://my.curated.co/codetengu/issues/32395

Curators of the week:

- @uranusjr
- @kkdai
- @drumrick

**Comment by uranusjr** [comment]
🎈

**Comment by kkdai** [comment]
我好了

**Comment by drumrick** [comment]
我也好了，只有三篇...

**Comment by saiday** [comment]
@drumrick 發現你的那篇 [了解一下 Google Art & Culture 在幹嘛](https://medium.com/@drumrick/f3ec0655c5be) 還是 Draft～

**Comment by uranusjr** [comment]
📕
