### ISSUE TITLE
Weekly issue 125 will be published on 2018/04/30 - @vinta, @fukuball

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#154]
See: https://my.curated.co/codetengu/issues/32546

Curators of the week:

- @vinta
- @fukuball

**Comment by vinta** [comment]
@yhsiang 別忘了這禮拜有你喔～

**Comment by vinta** [comment]
Scheduled.

**Comment by vinta** [comment]
@yhsiang 沒關係沒關係，看你什麼時候比較不忙再跟我說

**Comment by yhsiang** [comment]
@vinta 128 應該可以？
