### ISSUE TITLE
Weekly issue 131 will be published on 2018/06/11 - @uranusjr, @drumrick, @allanlei

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#160]
See https://my.curated.co/codetengu/issues/33018

Curators of the week:

- @uranusjr
- @drumrick
- @allanlei

Please do not hesitate to leave a comment if you have any questions.

**Comment by vinta** [comment]
啊，今天已經禮拜三了。不如下禮拜就休刊一次好了。

而且好像差不多可以再約一次吃飯了啊～

**Comment by kkdai** [comment]
約約... 之前都跟不到啊..
