### ISSUE TITLE
第三次碼天狗聚餐

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#161]
距離上一次聚餐已經過了一年了，也有不少新加入的成員，似乎是時候再約一次了啊。先麻煩大家挑一下自己有空的日期，時間應該會是晚上 19:00 ~ 21:00 這個期間。

想吃什麼歡迎提議，確定日期之後我再去訂位。

---

我有 email 給各位 Doodle 的連結，大家記得填一下啊～

**Comment by vinta** [comment]
還沒去填時間的人麻煩收個信填一下啊，沒收到信或是沒辦法去的人可以跟我說一下～

不然沒有意外的話，聚餐的時間應該就會定在 2018/7/10 禮拜二了。

**Comment by uranusjr** [comment]
沒收到

**Comment by vinta** [comment]
時間和地點已經確定了，我有寄一封 email 給大家。沒收到信的人再跟我說啊～

**Comment by vinta** [comment]
大家不要忘了啊，明天 2018/07/25 19:30 就是聚餐的日子啦～

**Comment by tzangms** [comment]
好！
