### ISSUE TITLE
Weekly issue 132 will be published on 2018/06/25 - @mingderwang, @chiahsien, @theJian

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#162]
See https://my.curated.co/codetengu/issues/33019

Curators of the week:

- @mingderwang
- @chiahsien
- @theJian

Please do not hesitate to leave a comment if you have any questions.

**Comment by theJian** [comment]
:ok_hand:

**Comment by chiahsien** [comment]
我好了
