### ISSUE TITLE
Weekly issue 133 will be published on 2018/07/02 - @vinta, @yhsiang, @wancw

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#163]
See https://my.curated.co/codetengu/issues/33297

Curators of the week:

- @vinta
- @yhsiang
- @wancw

Please do not hesitate to leave a comment if you have any questions.

**Comment by yhsiang** [comment]
收到！

**Comment by wancw** [comment]
Got it!

**Comment by fukuball** [comment]
@vinta 我這個禮拜真的太忙，看起來無法了，你可以找其他人幫忙這週嗎？

**Comment by vinta** [comment]
@fukuball 好喔。不過現在已經禮拜四了，再安排人可能是有點太趕，那這週就先兩個人啦。

**Comment by wancw** [comment]
完成。最近實在太廢了，只能勉強湊出 4 篇……

**Comment by yhsiang** [comment]
不好意思，趕 App，差點忘了！

**Comment by vinta** [comment]
剛剛發出去了，關！
