### ISSUE TITLE
Weekly issue 134 will be published on 2018/07/09 - @saiday, @johnlinvc

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#164]
See https://my.curated.co/codetengu/issues/33386

Curators of the week:

- @saiday
- @johnlinvc

Please do not hesitate to leave a comment if you have any questions.

**Comment by saiday** [comment]
@kkdai 可能忘記了嗎？

**Comment by kkdai** [comment]
糟糕，上週都在趕東西。沒注意到。

Saiday <notifications@github.com>於 2018年7月9日 週一，上午3:08寫道：

**Comment by kkdai** [comment]
報告主編，其實我有三篇寫好的。可以幫我排一下嗎？  在外面用手機不好版。

Evan Lin <evanslin@gmail.com>於 2018年7月9日 週一，上午9:38寫道：

**Comment by saiday** [comment]
娃，抱歉，看到時來不及，已經發出去了

**Comment by kkdai** [comment]
沒關係 sorry .. 幫我排到下個禮拜吧... 感謝
