### ISSUE TITLE
Weekly issue 135 will be published on 2018/07/23 - @vinta, @kako0507, @kkdai

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#165]
See https://my.curated.co/codetengu/issues/33463

Curators of the week:

- @vinta
- @kako0507
- @kkdai

It's a pretty busy week, and we need to postpone the publication date for a week. "We apologize for the inconvenience." 👽

Please do not hesitate to leave a comment if you have any questions.

**Comment by kako0507** [comment]
結果剛剛才發現這禮拜的沒發出去 @vinta 還安好嗎

**Comment by vinta** [comment]
@kako0507 上禮拜事情太多，延一個禮拜吼
7/23 才要發
