### ISSUE TITLE
Weekly issue 137 will be published on 2018/08/06 - @mingderwang, @allanlei, @theJian

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#167]
See https://my.curated.co/codetengu/issues/33689

Curators of the week:

- @mingderwang
- @allanlei
- @theJian 

Please do not hesitate to leave a comment if you have any question.

**Comment by wancw** [comment]
這星期事情有點多，不知道有沒有人可以先幫忙頂一下？ @@

**Comment by theJian** [comment]
@wancw If you need help don't bother to hit me up

**Comment by vinta** [comment]
@theJian 沒想到你生產力這麼旺盛，以後多靠你了 👍

**Comment by wancw** [comment]
@theJian 感謝支援！

**Comment by mingderwang** [comment]
got it.

Ming

**Comment by mingderwang** [comment]
done!

**Comment by theJian** [comment]
我也蛋了

**Comment by allanlei** [comment]
:100:
