### ISSUE TITLE
Weekly issue 138 will be published on 2018/08/20 - @saiday, @wancw, @LucienLee

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#168]
See https://my.curated.co/codetengu/issues/33779

Curators of the week:

- @saiday
- @wancw
- @LucienLee 

Please do not hesitate to leave a comment if you have any question.

---

拍謝，最近事情比較多，現在才公布，所以晚一週發刊～

**Comment by saiday** [comment]
好的

**Comment by wancw** [comment]
Got it!
