### ISSUE TITLE
Weekly issue 139 will be published on 2018/08/27 - @fukuball, @yhsiang, @johnlinvc

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#169]
See https://my.curated.co/codetengu/issues/33925

Curators of the week:

- @fukuball
- @yhsiang
- @johnlinvc 

Please do not hesitate to leave a comment if you have any question.

**Comment by johnlinvc** [comment]
no problem.

**Comment by johnlinvc** [comment]
Done, 我有加一個 iplayground 的宣傳到 sponsor, 不知道可不可以幫我加進這期呢？謝謝

**Comment by vinta** [comment]
Done.
