### ISSUE TITLE
Weekly issue 140 will be published on 2018/09/03 - @vinta, @kako0507, @kkdai, @yhsiang

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#170]
See https://my.curated.co/codetengu/issues/34000

Curators of the week:

- @vinta
- @kako0507
- @kkdai
- @yhsiang

Please do not hesitate to leave a comment if you have any question.

**Comment by kkdai** [comment]
收到

**Comment by vinta** [comment]
@yhsiang 這禮拜有你喔，母湯袂記

**Comment by kkdai** [comment]
完成..

**Comment by vinta** [comment]
Done.
