### ISSUE TITLE
Weekly issue 142 will be published on 2018/09/17 - @saiday, @fukuball, @mingderwang

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#172]
See https://my.curated.co/codetengu/issues/34135

Curators of the week:

- @saiday
- @fukuball
- @mingderwang

Please do not hesitate to leave a comment if you have any question.

**Comment by LucienLee** [comment]
這週正面臨人生的一個颱風、地震跟恐攻的集合中，想請求 Shift 到下一週。

**Comment by vinta** [comment]
@LucienLee 好喔。

@fukuball 你能不能頂一下？看你這禮拜好像寫了不少技術文章？

**Comment by fukuball** [comment]
@vinta 好啊，沒問題

**Comment by mingderwang** [comment]
I got it.

**Comment by mingderwang** [comment]
@fukuball   我們在同ㄧ期. 這次我不寫 blockchain 相關的議題.

**Comment by fukuball** [comment]
@mingderwang ok, 我這次應該都跟 blockchain 比較相關
