### ISSUE TITLE
Weekly issue 143 will be published on 2018/10/01 - @chiahsien, @wancw, @LucienLee

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#173]
See https://my.curated.co/codetengu/issues/34298

Curators of the week:

- @chiahsien
- @wancw
- @LucienLee

Sorry for the late announcement (again), so we need to postpone the publication date for a week. "We apologize for the inconvenience." 👽

Please do not hesitate to leave a comment if you have any question.

**Comment by wancw** [comment]
Roger that

**Comment by LucienLee** [comment]
got it!

**Comment by chiahsien** [comment]
我好了

**Comment by LucienLee** [comment]
內容昨天完成了
