### ISSUE TITLE
找一位台灣人以外的 curator

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#24]
我們現在 weekly 的內容已經很多元了，那就再多元一點，我覺得或許可以找個中國或是香港的 curator。也順便拓展一下海外市場，畢竟我們有很多訂閱者其實是中國人。

**Comment by kevingo** [comment]
good.

**Comment by kkdai** [comment]
來推薦一個國外的 curator 

https://www.facebook.com/jewelychu

主要是因為他在 Mooc 相關文章裡面寫 [CS50：一堂超過 800 個哈佛學生選修的「硬課」，魅力何在？](http://www.inside.com.tw/2014/12/17/harvard-cs50)

看大家覺得如何...

**Comment by wancw** [comment]
而且會是第一位女性 curator？

**Comment by fukuball** [comment]
@kkdai 不確定她對這樣的宅物有沒有興趣...

**Comment by vinta** [comment]
Yeah, I found one! Close!
