### ISSUE TITLE
自動化 CodeTengu 的例行事項、瑣事

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#62]
因為最近剛好在研究 [AWS Lambda](https://aws.amazon.com/lambda/)
就想到其實可以把一些 CodeTengu 每個禮拜要做的例行事項透過程式自動化
詳見 https://github.com/CodeTengu/lambdabaku

以下是我目前想到的可以自動化的事：
- [ ] 自動排程 Weekly 每一期的 curator 名單 >> #63 
- [ ] 當期的 Weekly 發刊後，自動在 GitHub issues 公布下一期的 curator 名單
- [ ] 當期的 Weekly 發刊後，自動關掉舊的公布 curator 名單的 issue
- [x] 當期的 Weekly 發刊後，自動分享到 Twitter
- [x] 當期的 Weekly 發刊後，自動分享到 Facebook（透過 Twitter）
- [x] 當期的 Weekly 發刊後，自動分享到微博（透過 IFTTT）
- [x] 定期把 Curated 上的資料抓回來存到我們自己的資料庫（DynamoDB）
- [ ] 定期把 Weekly 過去幾期的文章分享到 Twitter 和 Facebook

開放 API：
- [x] `/v1/issues/` 
- [x] `/v1/issues/{issue_number}` 

延伸閱讀：
- [湾区日报是如何运作的？](https://wanqu.co/blog/2015-05-24-behind-the-scenes.html)

**Comment by vinta** [comment]
剛剛發現原來 Curated 有支援 Zapier（類似 IFTTT 的服務）
https://zapier.com/app/explore/curated/#content

這樣有些事似乎可以直接用 Zapier 做掉
不用寫程式
可是這樣就不酷了吶

**Comment by kkdai** [comment]
可以考慮都用 IFTTT/Zapier  來串，如果缺少的服務在寫個 Server 來串．
就像我的 twitter 寫好後透過 IFTTT 轉到所有相關的 Social Media ，但是由於沒有 Plurk ，所以自己開發個 Webhook 給 IFTTT 用．

畢竟 IFTTT/Zapier 免費又相對穩定(?)
