### ISSUE TITLE
設計一個自動選出 curator 名單的演算法

### ISSUE THREAD

**Issue by vinta** [CodeTengu/HyakkiYagyo#63]
在 https://github.com/CodeTengu/headquarters/issues/62 有提到
因為想要「自動排程 Weekly 每一期的 curator 名單」這件事
能夠用程式每個禮拜從現有的 curator 名單中選出三位
但是我們又不能只是單純地從所有人選裡「隨機」選出三位來當 curator

所以或許得設計一個「假隨機」的演算法
至少要滿足以下幾個條件：
- 每次從所有 curator 名單中選出三個人
- 每個 curator 的出場機會盡可能一樣
- 每一期 curator 名單的組合盡可能不一樣
- 能夠隨時新增或移除 curator

大家有什麼想法的話儘管提出來。

**Comment by kkdai** [comment]
要能加入篩選系統，配合有些 Curator 暫時幾個月不能加入名單

**Comment by vinta** [comment]
如果是這個情況的話應該是直接從 pool 裡移掉就好？

**Comment by theJian** [comment]
这样子呢?

1. 设置一个 `c_lst` : curator 列表, key 是 curator ID, 对应的 value 是获选机率, 第一次运行时初始化, 初始 value 都为一个固定值, 假定是 d

2. 根据 c_lst 中的概率来随机选举 3 个 curator

3. 修改这三个 curator 对应的 `c_lst` 中的机率, 重置为 d

4. 这三个之外的 curator 对应的 `c_lst` 中的机率增加 k

5. 保存 `c_lst`, 用来作为下次随机选举

这样的话这一轮的 curator 下次再次获选的机率是最低的(d), 而长期未获选的 curator 会不断累计 k 获选概率不断增加

**Comment by theJian** [comment]
这份 `c_lst` 数据也可以同步到这个 repo, 这样所有 curator 可以查看了解自己下次被抽选的概率, 做好准备

**Comment by uranusjr** [comment]
這樣似乎無法考慮到領域重複的問題。這應該是最麻煩的部分。

**Comment by wancw** [comment]
寫了一個概念實作，重點流程如下：

1. 先列出所有組合 `C(n 取 3)` 並排除主題重複的
2. 算出每個人在前述組合裡的出現次數，用來計算權重
3. 從還沒選過的人中用 weighted choice 隨機挑選
    1. 當人數不夠時，先把剩下的人都排進去，再重新洗牌挑選不夠的數量
    2. 洗牌時要避免選到跟上一期重複的人

```py
from itertools import combinations
from numpy.random import choice

TOPICS = {
    'vinta'      : ['Python', 'JavaScript', 'MySQL', 'NoSQL', 'DevOps'],
    'saiday'     : ['iOS', 'Android'],
    'tzangms'    : ['Python', 'JavaScript', 'Growth Hacking', '技術團隊管理', 'Instagram'],
    'fukuball'   : ['PHP', '機器學習'],
    'wancw'      : ['JavaScript', 'Android', 'Instagram'],
    'adamp33'    : ['JavaScript', 'CSS'],
    'mingderwang': ['Go', 'DevOps'],
    'chiahsien'  : ['iOS' ],
    'hiroshiyui' : ['Erlang', 'Elixir'],
    'uranusjr'   : ['有的沒的'],
    'kkdai'      : ['Go'],
}

CURATORS_PER_ISSUE = 3


def gen_for_issues(issue_count):
    # initial parameters
    curators = list(TOPICS.keys())
    curator_appearance_count = count_appearance(curators)

    # states between issues
    curated = set()
    candidates = set(curators)
    last_curators = set()

    for i in range(issue_count):
        # Use all left if not enough
        if len(candidates) > CURATORS_PER_ISSUE:
            choiced = []
            need_count = CURATORS_PER_ISSUE
            skip_set = set()
        else:
            choiced = list(candidates)
            need_count = CURATORS_PER_ISSUE - len(candidates)
            skip_set = last_curators

            curated = set(choiced)
            candidates = set(curators) - curated

        # count -> weight
        cand_list = list(candidates - skip_set)
        weights = cal_weight(cand_list, curator_appearance_count)

        # choose
        choiced = choiced + list(choice(cand_list, p=weights, size=need_count, replace=False))
        print(choiced)

        # update new state
        last_curators = set(choiced)
        curated |= last_curators
        candidates -= last_curators


def count_appearance(cs):
    cnts = {}
    for comb in combinations(cs, CURATORS_PER_ISSUE):
        if have_overlaped_topics(comb):
            continue
        for c in comb:
            cnts[c] = cnts.get(c, 0) + 1
    return cnts;


def have_overlaped_topics(cs):
    for c1, c2 in combinations(cs, 2):
        if set(TOPICS[c1]) & set(TOPICS[c2]):
            return True
    return False


def cal_weight(cs, cnts):
    total_count = 0
    for c in cs:
        total_count += cnts[c]
    return [ cnts[c]/total_count for c in cs ]


gen_for_issues(10)
```

**Comment by kkdai** [comment]
@wancw 讚唷。要不要我們就開個repo開始做吧？

**Comment by vinta** [comment]
我開了一個 repo https://github.com/CodeTengu/lambdabaku
來放 AWS Lambda 的 code
目前是用 [apex](https://github.com/apex/apex) 來 deploy
可以用 Go, Java, Node.js, Python 這幾種語言來寫 Lambda function

有沒有人有興趣解一下這個 issue？
大家應該都有權限可以 push

--

不過我目前還沒有很確定應該怎麼存 GitHub access token（用來開關 GitHub issue）之類的資料
現在是存在 DynamoDB 裡
runtime 的時候才去拿

**Comment by wancw** [comment]
I will take this!

**Comment by vinta** [comment]
不過我覺得只要滿足「每一期的 curator 名單的組合盡可能不一樣」條件
領域重複的問題其實可以忽略
畢竟每個人負責的領域並不是硬性的規定

**Comment by wancw** [comment]
我想先做

* 全部 curator 輪過一遍才會重複
* 兩期間不要重複

其他就用亂數選，搞不好已經可以滿足大多數的狀況了。

**Comment by uranusjr** [comment]
第一點敢容易做欸，感覺還是加權比較容易？用個與 n（連續輪空次數）相關的函數來加權之類的應該很方便。一開始可能可以用 `n**2` 之類的，這樣也不可能兩期重複（輪空次數 0）。
